add .env check to script/env

diff --git a/script/env b/script/env
--- a/script/env
+++ b/script/env
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if [ ! -f .env ]; then
+  echo "missing: .env -- create it first with:  cp .template.env .env" >&2
+  exit 1
+fi
+
 if [ -z "${ENV_LOADED+x}" ]; then
     export $(grep -v '^#' .env | xargs)
     export ENV_LOADED=1
